### ISSUE TITLE
Unable to download rlog.bz2 files

### ISSUE THREAD

**Issue by Hubblesphere** [commaai/explorer#110]
**Device information**
> dongle_id | e977b6aeb5565611
>
> Segments: 
> e977b6aeb5565611\|2021-06-16--20-07-31
> e977b6aeb5565611\|2021-06-16--20-03-45
> e977b6aeb5565611\|2021-06-16--19-25-58
> e977b6aeb5565611\|2021-06-16--19-09-14

>
> version = "0.8.5-d4ab1f1e2-2021-06-07T22:13:55",
    dirty = false,
    gitCommit = "145b222f0d45a8087215d5700240f58e654e7393",
    gitBranch = "devel-staging",
    
    
    

**Context:** these are several drives separated by ignition cycles. First ones had openpilot enabled and the rest were done in dashcam mode. 

Also, raw log upload was toggle on after the drives were complete to upload them.

**Issue:** Uploads appear complete, but rlogs are not downloadable. 

The first segment from this drive (e977b6aeb5565611|2021-06-16--18-59-08) has rlogs available and CAN data available in Cabana. All others do not.

**Comment by gregjhogan** [comment]
This is a preserved route, you probably preserved it before it was done uploading (only preserving some of the files).

unpreserve it and you will be able to download the files if it is recent
preserve it after it is done uploading you will also be able to download the files
