### ISSUE TITLE
App no longer shows has an option to show Openpilot overlay.

### ISSUE THREAD

**Issue by jdial1** [commaai/explorer#130]
The app used to have a button which allowed a user to see an overlay of the open pilot system mapping where it is controlling the vehicle, this included the overlaid sidelines and tentacle middle line.

https://imgur.com/a/AP9joWx

**Comment by adeebshihadeh** [comment]
This was removed because the model packets got too big to keep in the qlogs (small subset of the full resolution logs). Currently, the supported way to get a replay with an overlay is by building openpilot's UI on your PC.
