### ISSUE TITLE
Support accounts without a device

### ISSUE THREAD

**Issue by andyh2** [commaai/explorer#56]
Explorer currently hangs on loading spinner after logging in with an account that does not have any paired devices. Instead, it should display an appropriate zero-state with pointers on how to buy/pair a device.

**Comment by maxmetcalfe** [comment]
It looks like this has been fixed. When you log in without a paired device, you see the "Shared device" in the device list and "Get started with comma two" with a link to the shop.

**Comment by simplemachine92** [comment]
I'm wondering how I can test various features and contribute to the repo without a comma, it doesn't seem this is an option any longer?

**Comment by jwooning** [comment]
Besides using the demo there isn't really any option. We would also very much appreciate PRs adding tests for the current state of connect, that should also be possible without a device.
