### ISSUE TITLE
Add Warning if Full-Res footage isn't yet uploaded

### ISSUE THREAD

**Issue by VirtuallyChris** [commaai/explorer#91]
A warning dialog should come up if the drive's full-res footage isn't uploaded over WiFi. "Full Resolution Footage Not Uploaded: Connect to WiFi" or something along those lines.

**Comment by gregjhogan** [comment]
explorer only plays qcamera files (getting your device on wifi won't help) and explorer won't support anything else until browsers can play the HEVC files or we support direct streaming/transcoding from the device

**Comment by adeebshihadeh** [comment]
covered by #87 and #62
